### ISSUE TITLE
Cube Timer 

### ISSUE THREAD

**Issue by DieInhaltsangabe** [DieInhaltsangabe/AppProgrammingFlutter#3]
Gibt eine Mischung vor, welche gelöst werden soll und mithilfe
eines Timers gestoppt werden soll.

**Comment by DieInhaltsangabe** [comment]
@EleckTroniiKz Ich hab ein Ungeziefer gefunden. Wenn du mehr als 3-4 Logs hast kannst du die nicht ansehen obwohl das ganze ein Scrollable ist. 👀

**Comment by ucc-et** [comment]
@DieInhaltsangabe  oh ok gut gesehen :D  ich schaue es mir spöter an ^^

**Comment by ucc-et** [comment]
@DieInhaltsangabe Kann es nicht reproducen. 
![grafik](https://github.com/DieInhaltsangabe/AppProgrammingFlutter/assets/73250162/6e01804d-4540-4328-a36a-74d618c25e08)
Man sieht immer maximal 2 1/2. Wenn man dann scrollt, dann sieht man die anderen
![grafik](https://github.com/DieInhaltsangabe/AppProgrammingFlutter/assets/73250162/60e29f04-5c8f-453f-a5ba-cc1259dfe7b3)

**Comment by ucc-et** [comment]
@DieInhaltsangabe  Musst halt darauf achten, dass das ding gescrollt wird in dem du mit der Maus drauf clickst und ziehst. Also nicht mit dem scrollwheel
