### ISSUE TITLE
Cube TImer Log

### ISSUE THREAD

**Issue by DieInhaltsangabe** [DieInhaltsangabe/AppProgrammingFlutter#4]
Es wird ein Log gespeichert mit Datum, und Geschwindigkeit und Cube.

**Comment by ucc-et** [comment]
Den Cube können wir nicht speichern, weil nicht immer festgelegt wird, ob ein Cube generiert wurde oder nicht.

**Comment by ucc-et** [comment]
aber Datum und Zeit is gespeichert :)
